from odoo import models, fields, api
from datetime import date, datetime, time, timedelta
from pytz import timezone



class ReportXlsxConsumptionWise(models.AbstractModel):
    _name = 'report.pakgulf_attendance_reports.monthly_report_xls'
    _description = 'Report Wizard For Excal Xlsx File'
    _inherit = 'report.report_xlsx.abstract'

    def generate_xlsx_report(self, workbook, data, res):
        sheet = workbook.add_worksheet('Employee Attendance Report')

        text_wrap1 = workbook.add_format()
        text_wrap1.set_bold()
        text_wrap1.set_bg_color('#A2B5CD')
        text_wrap1.set_font_color('black')
        text_wrap1.set_font_size("15")
        text_wrap1.set_align('center')
        text_wrap1.set_text_wrap()
        text_wrap1.set_border()

        text_wrap = workbook.add_format()
        text_wrap.set_align('center')
        text_wrap.set_bold()
        text_wrap.set_font_color('white')
        text_wrap.set_bg_color('#303030')
        text_wrap.set_text_wrap()
        text_wrap.set_border()

        text_wrap20 = workbook.add_format()
        text_wrap20.set_align('center')
        text_wrap20.set_bold()
        text_wrap20.set_font_color('white')
        text_wrap20.set_bg_color('#303030')
        text_wrap20.set_text_wrap()
        text_wrap20.set_border()
        text_wrap20.set_font_size("8")

        text_wrap3 = workbook.add_format()
        text_wrap3.set_align('left')
        text_wrap3.set_bold()
        text_wrap3.set_border()
        text_wrap3.set_font_color('black')
        text_wrap3.set_text_wrap()

        text_wrap4 = workbook.add_format()
        text_wrap4.set_align('center')
        text_wrap4.set_font_color('black')
        text_wrap4.set_text_wrap()
        text_wrap4.set_border()

        text_wrap5 = workbook.add_format()
        text_wrap5.set_bg_color('#EEDFCC')
        text_wrap5.set_align('center')
        text_wrap5.set_font_color('black')
        text_wrap5.set_text_wrap()
        text_wrap5.set_border()

        text_wrap6 = workbook.add_format()
        text_wrap6.set_bg_color('#EEDFCC')
        text_wrap6.set_align('center')
        text_wrap6.set_font_color('black')
        text_wrap6.set_font_size('10')
        text_wrap6.set_text_wrap()
        text_wrap6.set_border()

        text_wrap7 = workbook.add_format()
        text_wrap7.set_bg_color('#CDC0B0')
        text_wrap7.set_align('center')
        text_wrap7.set_font_color('black')
        text_wrap7.set_font_size('10')
        text_wrap7.set_text_wrap()
        text_wrap7.set_border()

        text_wrap8 = workbook.add_format()
        text_wrap8.set_bg_color('#8B8378')
        text_wrap8.set_align('center')
        text_wrap8.set_font_color('black')
        text_wrap8.set_font_size('10')
        text_wrap8.set_text_wrap()
        text_wrap8.set_border()

        sheet.set_column('A:A', 5)
        sheet.set_column('B:B', 15)
        sheet.set_column('C:D', 25)
        sheet.set_column('E:E', 35)
        sheet.set_column('F:F', 30)
        sheet.set_column('G:I', 30)
        sheet.set_column('J:AN', 10)
        sheet.set_column('AO:AO', 15)
        sheet.set_column('AP:AP', 25)
        sheet.set_column('AQ:AR', 15)
        sheet.merge_range(0, 10, 1, 25, self.env.company.name, text_wrap1)
        sheet.merge_range(2, 10, 3, 25, 'Employee Attendances Report', text_wrap1)

        row = 1
        col = 1
        sheet.write(row, col, 'From Date:', text_wrap3)
        
        row = 3
        col = 1
        sheet.write(row, col, 'To Date:', text_wrap3)
        new_format_new = "%d-%m-%y %I:%M %p"
        row = 1
        col = 40
        sheet.write(row, col, 'Generated By:', text_wrap3)
        sheet.write(1, 41, self.env.user.name)
        row = 3
        col = 40
        sheet.write(row, col, 'Print On:', text_wrap3)
        sheet.write(3, 41, str(datetime.now().strftime(new_format_new)))

        row = 5
        col = 0
        sheet.write(row, col, 'Sr No', text_wrap)
        # sheet.write(row, col + 1, 'Eng Date', text_wrap)
        sheet.write(row, col + 1, 'Code', text_wrap)
        sheet.write(row, col + 2, 'Name', text_wrap)
        sheet.write(row, col + 3, 'Designation', text_wrap)
        sheet.write(row, col + 4, 'Department', text_wrap)
        sheet.write(row, col + 5, 'Sub Department', text_wrap)
        sheet.write(row, col + 6, 'Location', text_wrap)
        sheet.write(row, col + 7, 'Company', text_wrap)
        sheet.write(row, col + 8, 'In/Out', text_wrap)
        sheet.write(row, col + 40, 'Total Days', text_wrap)
        sheet.write(row, col + 41, 'Total Hours Worked', text_wrap)
        sheet.write(row, col + 42, 'Total Absents', text_wrap)
        # sheet.write(row, col + 43, 'Comments', text_wrap)

        new_format = "%H:%M"
        data = self.env['pakgulf.emp.wise.attendance'].search([],limit=1,order="id desc")
        domain = [('company_id', '=', self.env.company.id)]
        if data.employee_ids:
            domain.append(('id', 'in', data.employee_ids.ids))
        if data.company_id:
            domain.append(('company_id', '=', data.company_id.id))
        if data.department_ids:
            domain.append(('department_id', 'in', data.department_ids.ids))
        else:
            department_ids = self.env["hr.employee"].search(domain,order="id asc").mapped('department_id')
            domain.append(('department_id', 'in', department_ids.ids))
        date_t = fields.Date.from_string(data.to_date)
        date_fro = fields.Date.from_string(data.from_date)
        days = []
        dateelis = []
        r = 8


        sheet.write(1, 2, str(data.to_date))
        sheet.write(3, 2, str(data.from_date))
        date_frommmm = date_fro
        while (date_frommmm <= date_t):
            r+=1
            datee = date_frommmm
            dateelis.append({'datee': datee, 'atte': ''})
            days.append({
                'datee': datee,
                'atte': '',
            })
            formatted_date = datee.strftime('%d %B')
            day_name = datee.strftime('%a')  # Get the day name
            sheet.write(row, col + r, formatted_date, text_wrap20)
            sheet.write(row + 1, col + r, day_name, text_wrap20)
            date_frommmm += timedelta(days=1)
        row += 1

        planning_record_test = self.env['hr.employee'].search(domain)
        sr = 0
        # total_work_hor = 0

        for emp in planning_record_test:
            row += 1
            c = 8
            sr += 1
            sheet.write(row, 0, sr, text_wrap5)
            sheet.write(row, 1, emp.barcode, text_wrap5)
            sheet.write(row, 2, emp.name, text_wrap5)
            sheet.write(row, 3, emp.job_id.name, text_wrap5)
            sheet.write(row, 4, emp.department_id.name , text_wrap5)
            sheet.write(row, 5, emp.department_id.parent_id.name , text_wrap5)
            categories = ', '.join(emp.category_ids.mapped('name'))
            sheet.write(row, 6, categories, text_wrap5)
            sheet.write(row, 7, emp.company_id.name , text_wrap5)
            sheet.write(row, 8, "In Time", text_wrap5)
            row += 1  # Move to the next row for Out Time
            sheet.write(row, 8, "Out Time", text_wrap7)
            row += 1  # Move to the next row for Work Hours
            sheet.write(row, 8, "Work Hours", text_wrap8)
            row += 1  # Move to the next row for Work Hours
            sheet.write(row, 8, "Planning", text_wrap8)

            day_work_hor = 0.0
            totat_wor = 0
            ro = 0
            wor = 0
            absents = 0
            total_work_hor = 0

            karachi_timezone = timezone("Asia/Karachi")
            for date in days:
                plan = 'No'
                c += 1
                ro += 1
                atendance = data.env['hr.attendance'].search(
                    [('employee_id', '=', emp.id), ('checkin_date', '=', date['datee'])])
                date['atte'] = ''
                checkin = ''
                checkout = ''
                work_hours = 0
                if atendance:
                    checkin = atendance.check_in.astimezone(karachi_timezone).strftime(new_format) if atendance.check_in else '---'
                    checkout = atendance.check_out.astimezone(karachi_timezone).strftime(new_format) if atendance.check_out else '----'
                    work_hours = atendance.worked_hours if atendance.worked_hours else 0
                    date['atte'] = 'P'
                    wor+=1
                    day_work_hor += atendance.worked_hours
                else:
                    leave = data.env["hr.leave"].search(
                        [('employee_id', '=', emp.id), ('state', '=', 'validate'), ('request_date_from', '<=', date['datee']), ('request_date_to', '>=', date['datee'])], limit=1)
                    if leave:
                        checkin = leave.holiday_status_id.work_entry_type_id.code
                        checkout = leave.holiday_status_id.work_entry_type_id.code
                        date['atte'] = leave.holiday_status_id.work_entry_type_id.code
                    else:
                        working_schedule = emp.resource_calendar_id.attendance_ids
                        if not working_schedule.filtered(lambda a: a.dayofweek == str(date['datee'].weekday())):
                            checkin = 'Rest Day'
                            checkout = 'Rest Day'
                            date['atte'] = 'Rest Day'
                        else:
                            checkin = 'A'
                            checkout = 'A'
                            date['atte'] = 'A'
                            absents += 1
                    # Determine if there is a working schedule for the day
                    start = datetime.strftime(date['datee'], '%Y-%m-%d 00:00:00')
                    end = datetime.strftime(date['datee'], '%Y-%m-%d 23:59:59')

                    # working_schedule = emp.resource_calendar_id.attendance_ids
                    working_schedule = self.env['planning.slot'].search([('resource_id','=', emp.resource_id.id),('start_datetime','>=', start),('end_datetime','<=', end)])
                    if working_schedule:
                        plan = 'Yes'
                    day_work_hor += atendance.worked_hours
                    totat_wor = day_work_hor

                sheet.write(row, c, plan, text_wrap8)  # Work Hours
                sheet.write(row - 3, c, checkin, text_wrap6)  # In Time
                sheet.write(row - 2, c, checkout, text_wrap7)  # Out Time
                try:
                    work_hours_int = round(work_hours)
                except (ValueError, TypeError):
                    work_hours_int = 0  # or handle the error appropriately

                sheet.write(row - 1, c, work_hours_int, text_wrap8)  # Work Hours
                sheet.write(row, 42, absents, text_wrap4)
            total_work_hor += totat_wor
            sheet.write(row, 40, len(days), text_wrap4)
            sheet.write(row, 41, round(total_work_hor, 2), text_wrap4)



