# -*- coding: utf-8 -*-
{
    'name': 'Sale Order Custom',
    'author': 'Alieh Vo',
    'website': '',
    'support': 'trungvyvo123@gmail.com',
    'category': 'Sales',
    'license': 'OPL-1',
    'summary': '',
    'description': """ """,
    'version': '17.0.1.2',
    'depends': ['sale_management', 'stock', 'product_expiry'],
    'application': True,
    'data': [
        'views/sale_view.xml',
        'views/pricelist.xml',
        'views/partner.xml',
        'views/account_tax.xml',
        'report/reports.xml',
        'report/sale_template.xml',
        'report/invoice_template.xml',
        'report/stock_template.xml',
    ],
    'images': ['static/description/background.jpg'],
    'auto_install': False,
    'installable': True,
    'price': 13,
    'currency': 'EUR',
}
