# from datetime import datetime
# import logging
# from odoo import models

# _logger = logging.getLogger(__name__)

# class ReportXlsxSalaryComWise(models.AbstractModel):
#     _name = 'report.opus_payroll_report.com_wise_xlsx'
#     _description = 'Report Wizard For Excel Xlsx File'
#     _inherit = 'report.report_xlsx.abstract'

#     def generate_xlsx_report(self, workbook, data, objs):
#         # Formatting setup
#         sheet = workbook.add_worksheet('Payroll Report')
#         bold = workbook.add_format({'bold': True})
#         date_format = workbook.add_format({'num_format': 'yyyy-mm-dd', 'align': 'center', 'border': 1})
#         text_wrap3 = workbook.add_format({'align': 'center', 'bold': True, 'border': 1, 'font_color': 'black', 'text_wrap': True})
#         text_wrap2 = workbook.add_format({'align': 'center', 'bold': True, 'border': 1})
#         text_wrap1 = workbook.add_format({'align': 'center', 'bold': True, 'font_color': 'black', 'text_wrap': True, 'border': 1})
#         text_wrap = workbook.add_format({'align': 'center', 'bold': True, 'font_color': 'black', 'text_wrap': True, 'border': 1})
#         cell_format = workbook.add_format({'num_format': '#,###', 'align': 'center', 'border': 1})
#         cell_for = workbook.add_format({'num_format': '#,###', 'align': 'center', 'bold': True, 'border': 1})

#         # Column setup
#         columns = [
#             ('FXA', 'Fixed Allowance', 0),
#             ('BONUS', 'Bonus', 0),
#             ('BASIC', 'Basic Salary', 0),
#             ('HA', 'House Allowance', 0),
#             ('UA', 'Utility Allowance', 0),
#             ('OT', 'Overtimes', 0),
#             ('LOAN/SAL', 'Loan', 0),
#             ('AR', 'Arrears', 0),
#             ('PF', 'PF Employee', 0),
#             ('EOBI', 'EOBI Employee', 0),
#             ('PESSI', 'PESSI Employer', 0),
#             ('PFEM', 'PF Employer', 0),
#             ('EOBIE', 'EOBI Employer', 0),
#             ('ADV/SAL', 'Staff Advances', 0),
#             ('DEDUCTION', 'Other Deduction', 0),
#             ('IT', 'Income Tax', 0),
#             ('NET', 'Total Payables', 0),
#         ]

#         # Identify columns with non-zero values
#         report_data, days_in_month = objs.get_report_data()
#         sheet.set_column('B:AF', 25)

#         # Headers and title setup
#         sheet.merge_range(0, 4, 1, 9, self.env.company.name, text_wrap1)
#         sheet.merge_range(2, 4, 3, 9, 'Batch/Employee Wise Payroll Report', text_wrap1)
#         sheet.write(1, 19, 'Generated By:', text_wrap3)
#         sheet.write(1, 20, self.env.user.name, text_wrap3)
#         sheet.write(2, 19, 'Print On:', text_wrap3)
#         sheet.write(2, 20, str(datetime.now()), text_wrap3)

#         data_wizard = self.env['opus.employees.payroll.report'].search([('id','=', int(data['id']))], limit=1, order='id desc')
#         if data_wizard.specific_date:
#             sheet.merge_range(5, 4, 6, 9, f"For The Month Of {data_wizard.specific_date.strftime('%B %Y')}", text_wrap1)
#         else:
#             if report_data:
#                 sheet.merge_range(5, 4, 6, 9, f"For The Month Of {report_data[0].date_from.strftime('%B %Y')}", text_wrap1)

#         for payslip in report_data:
#             for line in payslip.line_ids:
#                 for i, (code, header, total) in enumerate(columns):
#                     # Special handling for `ADV/SAL` based on category
#                     if code == 'ADV/SAL' and line.category_id.name == 'ADV/SAL' and line.total > 0:
#                         columns[i] = (code, header, total + line.total)
#                     elif line.code == code and line.total > 0:
#                         columns[i] = (code, header, total + line.total)

#         # Filter out columns with zero totals
#         visible_columns = [col for col in columns if col[2] > 0]

#         # Header setup
#         row = 9
#         col = 0
#         sr = 0
#         sheet.write(row, col, 'Sr. No.', text_wrap)
#         sheet.write(row, col + 1, 'Employee Code', text_wrap)
#         sheet.write(row, col + 2, 'Employee Name', text_wrap)
#         sheet.write(row, col + 3, 'Account #', text_wrap)
#         sheet.write(row, col + 4, 'Bank Name', text_wrap)
#         sheet.write(row, col + 5, 'Employment', text_wrap)
#         sheet.write(row, col + 6, 'Designations', text_wrap)
#         sheet.write(row, col + 7, 'Location', text_wrap)
#         sheet.write(row, col + 8, 'Region', text_wrap)
#         sheet.write(row, col + 9, 'DOJ', text_wrap)
#         sheet.write(row, col + 10, 'Days', text_wrap)
#         sheet.write(row, col + 11, 'Gross', text_wrap)
#         sheet.write(row, col + 12, 'No Of Days', text_wrap)
#         sheet.write(row, col + 13, 'Salary Payable', text_wrap)

#         for col_idx, (_, header, _) in enumerate(visible_columns):
#             sheet.write(row, col + 14 + col_idx, header, text_wrap)

#         row += 1

#         # Data setup
#         for payslip in report_data:
#             sr += 1
#             sheet.write(row, col, sr, cell_format)
#             sheet.write(row, col + 1, payslip.employee_id.barcode, cell_format)
#             sheet.write(row, col + 2, payslip.employee_id.name, cell_format)
#             sheet.write(row, col + 3, payslip.employee_id.bank_account_id.acc_number, cell_format)
#             sheet.write(row, col + 4, payslip.employee_id.bank_account_id.bank_id.name, cell_format)
#             sheet.write(row, col + 5, payslip.employee_id.contract_id.contract_type_id.name, cell_format)
#             sheet.write(row, col + 6, payslip.employee_id.job_id.name, cell_format)
#             sheet.write(row, col + 7, payslip.employee_id.work_location_id.name, cell_format)
#             sheet.write(row, col + 8, payslip.employee_id.region_wise_detail, cell_format)
#             sheet.write(row, col + 9, payslip.employee_id.contract_id.date_start, date_format)
#             sheet.write(row, col + 10, payslip.cal_days, cell_format)
#             sheet.write(row, col + 11, payslip.employee_id.contract_id.wage, cell_format)
#             no_of_days = sum(day.number_of_days for day in payslip.worked_days_line_ids if day.name == 'Attendance')
#             sheet.write(row, col + 12, no_of_days, cell_format)
#             salary_payable = sum([(payslip.contract_id.wage / payslip.cal_days) * day.number_of_days for day in payslip.worked_days_line_ids if day.name == 'Attendance'])
#             sheet.write(row, col + 13, round(salary_payable, 2), cell_format)


#             # Writing values for visible columns
#             col_offset = 14
#             for code, _, _ in visible_columns:
#                 value = sum(line.total for line in payslip.line_ids if (line.code == code or (code == 'ADV/SAL' and line.name == 'ADV/SAL')))
#                 sheet.write(row, col + col_offset, value, cell_format)
#                 col_offset += 1

#             row += 1

#         # Write totals only for visible columns
#         col_offset = 14
#         for _, _, total in visible_columns:
#             sheet.write(row, col + col_offset, round(total), cell_for)
#             col_offset += 1


import pytz
from datetime import datetime
import calendar
from odoo import models, fields, api
from datetime import datetime
import logging

_logger = logging.getLogger(__name__)


class ReportXlsxSalaryComWise(models.AbstractModel):
    _name = 'report.opus_payroll_report.com_wise_xlsx'
    _description = 'Report Wizard For Excel Xlsx File'
    _inherit = 'report.report_xlsx.abstract'

    def generate_xlsx_report(self, workbook, data, objs):
        sheet = workbook.add_worksheet('Salary Sheet')
        bold = workbook.add_format({'bold': True})
        date_format = workbook.add_format({'num_format': 'dd-mm-yyyy', 'align': 'center', 'border': 1})

        text_wrap2 = workbook.add_format()
        text_wrap2.set_bold()
        text_wrap2.set_align('center')
        text_wrap2.set_border()

        text_wrap1 = workbook.add_format()
        text_wrap1.set_bold()
        # text_wrap1.set_bg_color('#7A8B8B')
        text_wrap1.set_font_color('black')
        text_wrap1.set_align('center')
        text_wrap1.set_text_wrap()
        text_wrap1.set_border()
        header_wrap = workbook.add_format()
        header_wrap.set_bold()
        header_wrap.set_font_color('black')
        header_wrap.set_align('center')
        header_wrap.set_text_wrap()
        header_wrap.set_border()
        header_wrap.set_font_size("15")

        text_wrap = workbook.add_format()
        text_wrap.set_align('center')
        text_wrap.set_bold()
        text_wrap.set_font_color('black')
        text_wrap.set_text_wrap()
        text_wrap.set_border()

        text_wrap3 = workbook.add_format()
        text_wrap3.set_align('center')
        text_wrap3.set_bold()
        text_wrap3.set_border()
        text_wrap3.set_font_color('black')
        text_wrap3.set_text_wrap()
        # text_wrap3.set_bg_color('#848484')

        text_wrap4 = workbook.add_format()
        text_wrap4.set_align('center')
        text_wrap4.set_font_color('black')
        text_wrap4.set_text_wrap()
        text_wrap4.set_border()

        text_wrap5 = workbook.add_format()
        text_wrap5.set_align('center')
        text_wrap5.set_font_color('black')
        text_wrap5.set_text_wrap()
        text_wrap5.set_border()
        # text_wrap5.set_bg_color('#848484')

        cell_format = workbook.add_format({'num_format': '#,###'})
        cell_format.set_align('center')
        cell_format.set_border()
        cell_for = workbook.add_format({'num_format': '#,###'})
        cell_for.set_align('center')
        cell_for.set_bold()
        cell_for.set_border()

        sheet.set_column('B:AF', 25)
        employee_set = set()
        report_data, days_in_month = objs.get_report_data()
        # date_format = workbook.add_format({'num_format': 'yyyy-mm-dd'})

        # Headers
        sheet.merge_range(0, 4, 1, 9, self.env.company.name, header_wrap)
        sheet.merge_range(2, 4, 3, 9, 'Employee Wise Payroll Report', text_wrap1)
        sheet.write(1, 19, 'Generated By:', text_wrap3)
        sheet.write(1, 20, self.env.user.name, text_wrap3)
        sheet.write(2, 19, 'Print On:', text_wrap3)
        karachi_tz = pytz.timezone("Asia/Karachi")
        karachi_time = datetime.now(karachi_tz)
        sheet.write(2, 20, karachi_time.strftime("%d-%m-%Y %H:%M:%S"), date_format)
        # sheet.write(2, 20, str(datetime.now()), date_format)
        data_wizard = self.env['opus.employees.payroll.report'].search([('id','=', int(data['id']))], limit=1, order='id desc')
        if data_wizard.specific_date:
            # sheet.write(6, 5, data_wizard.specific_date.strftime('%B %Y'), text_wrap3)
            sheet.merge_range(5, 4, 6, 9, f"For The Month Of {data_wizard.specific_date.strftime('%B %Y')}", text_wrap1)

        else:
            if report_data:
                sheet.merge_range(5, 4, 6, 9, f"For The Month Of {report_data[0].date_from.strftime('%B %Y')}", text_wrap1)

        row = 9
        col = 0
        sr = 0
        sheet.write(row, col, 'Sr. No.', text_wrap)
        sheet.write(row, col + 1, 'Employee Code', text_wrap)
        sheet.write(row, col + 2, 'Employee Name', text_wrap)
        sheet.write(row, col + 3, 'CNIC', text_wrap)
        sheet.write(row, col + 4, 'Account #', text_wrap)
        sheet.write(row, col + 5, 'Bank Name', text_wrap)
        sheet.write(row, col + 6, 'Employment', text_wrap)
        sheet.write(row, col + 7, 'Designations', text_wrap)
        sheet.write(row, col + 8, 'Location', text_wrap)
        sheet.write(row, col + 9, 'Region', text_wrap)
        sheet.write(row, col + 10, 'DOJ', text_wrap)
        sheet.write(row, col + 11, 'Days', text_wrap)
        sheet.write(row, col + 12, 'Gross', text_wrap)
        sheet.write(row, col + 13, 'Fixed Allowance', text_wrap)
        sheet.write(row, col + 14, 'Bonus', text_wrap)
        sheet.write(row, col + 15, 'Basic Salary', text_wrap)
        sheet.write(row, col + 16, 'House Allowance', text_wrap)
        sheet.write(row, col + 17, 'Utility Allowance', text_wrap)
        sheet.write(row, col + 18, 'No Of Day', text_wrap)
        sheet.write(row, col + 19, 'Salary Payable', text_wrap)
        sheet.write(row, col + 20, 'Overtimes', text_wrap)
        sheet.write(row, col + 21, 'Loan', text_wrap)
        sheet.write(row, col + 22, 'Increment', text_wrap)
        sheet.write(row, col + 23, 'Reimbursement', text_wrap)
        sheet.write(row, col + 24, 'Arrears', text_wrap)
        sheet.write(row, col + 25, 'PF Employee', text_wrap)
        sheet.write(row, col + 26, 'EOBI Employee', text_wrap)
        sheet.write(row, col + 27, 'PESSI Employer', text_wrap)
        sheet.write(row, col + 28, 'PF Employer', text_wrap)
        sheet.write(row, col + 29, 'EOBI Employer', text_wrap)
        sheet.write(row, col + 30, 'Staff Advances', text_wrap)
        sheet.write(row, col + 31, 'Other Deduction', text_wrap)
        sheet.write(row, col + 32, 'Income Tax', text_wrap)
        sheet.write(row, col + 33, 'Total Payables', text_wrap)
        row += 1

        total_house_rent = 0
        total_utility_allo = 0
        total_overtime = 0
        total_loan = 0
        total_increment = 0
        total_reimbursement = 0
        total_arrear = 0
        total_pf_empl = 0
        total_eobi_empl = 0
        total_pessi_empl = 0
        total_pf_empr = 0
        total_eobi_empr = 0
        total_staff_adv = 0
        total_other_deduct = 0
        total_income_tax = 0
        total_bonus = 0
        total_fixed_allo = 0
        total_basic_salary = 0
        grand_total_payable = 0
        total_salary_payable = 0
        total_pf_till = 0
        total_wage = 0
        loan_sum = 0

        for payslip in sorted(report_data,reverse=False, key=lambda x: x.employee_id.barcode):
            sr += 1
            sheet.write(row, col, sr, cell_format)
            sheet.write(row, col + 1, payslip.employee_id.barcode, cell_format)
            sheet.write(row, col + 2, payslip.employee_id.name, cell_format)
            sheet.write(row, col + 3, payslip.employee_id.identification_id, cell_format)
            sheet.write(row, col + 4, payslip.employee_id.bank_account_id.acc_number, cell_format)
            sheet.write(row, col + 5, payslip.employee_id.bank_account_id.bank_id.name, cell_format)
            sheet.write(row, col + 6, dict(payslip.employee_id._fields['employment'].selection).get(payslip.employee_id.employment), cell_format)
            sheet.write(row, col + 7, payslip.employee_id.job_id.name, cell_format)
            sheet.write(row, col + 8, payslip.employee_id.work_location_id.name, cell_format)
            sheet.write(row, col + 9, payslip.employee_id.region_wise_detail, cell_format)
            sheet.write(row, col + 10, payslip.employee_id.contract_id.date_start, date_format)
            sheet.write(row, col + 11, payslip.cal_days, cell_format)
            # sheet.write(row, col + 10, days_in_month, cell_format)
            sheet.write(row, col + 12, payslip.employee_id.contract_id.wage, cell_format)
            total_wage += payslip.employee_id.contract_id.wage
            # sheet.write(row, col + 12, payslip.employee_id.contract_id.wage,cell_format)

            house_rent_allo = 0
            utility_allo = 0
            overtime = 0
            loan = 0
            increment = 0
            reimbursement = 0
            arrear = 0
            pf_empl = 0
            eobi_empl = 0
            pessi_empl = 0
            pf_empr = 0
            eobi_empr = 0
            staff_adv = 0
            other_deduct = 0
            income_tax = 0
            bonus = 0
            fixed_allo = 0
            basic_salary = 0
            total_payable = 0
            pf_till = 0
            salary_payable = 0
            number_of_days = 0
            for days in payslip.worked_days_line_ids:
                if days.name == 'Attendance':
                    number_of_days += days.number_of_days
                    salary_payable += (payslip.contract_id.wage / payslip.cal_days) * number_of_days
                    total_salary_payable += salary_payable
            # pessi_empl = salary_payable * 0.06
            # total_pessi_empl += pessi_empl
            increment = sum(payslip.contract_id.increment_detail_ids.filtered(lambda x:x.date <= payslip.date_from and x.date >= payslip.date_to).mapped('amount'))
            # increment = sum(payslip.contract_id.increment_detail_ids.mapped('amount'))
            total_increment += increment

            for line in payslip.line_ids:
                if line.code == 'HA':
                    house_rent_allo = house_rent_allo + line.total
                    total_house_rent += house_rent_allo
                if line.code == 'UA':
                    utility_allo = utility_allo + line.total
                    total_utility_allo += utility_allo
                if line.code == 'OT':
                    overtime = overtime + line.total
                    #total_overtime += overtime
                    total_overtime += line.total
                if 'LOAN/SAL' in line.name:
                    loan += line.total
                    total_loan += loan
                # if line.code == 'INC':
                #     increment += line.total
                #     total_increment += increment
                if line.code == 'REIMBURSEMENT':
                    reimbursement += line.total
                    total_reimbursement += reimbursement
                if line.code == 'AR':
                    arrear = arrear + line.total
                    total_arrear += arrear
                if line.code == 'PF':
                    pf_empl = pf_empl + line.total
                    total_pf_empl += pf_empl
                if line.code == 'EOBI':
                    eobi_empl = eobi_empl + line.total
                    total_eobi_empl += eobi_empl
                if line.code == 'PESSI':
                    pessi_empl = pessi_empl + line.total
                    total_pessi_empl += pessi_empl
                if line.code == 'PFEM':
                    pf_empr = pf_empr + line.total
                    total_pf_empr += pf_empr
                if line.code == 'EOBIE':
                    eobi_empr = eobi_empr + line.total
                    total_eobi_empr += eobi_empr
                if 'ADV/SAL' in line.name:
                    staff_adv = staff_adv + line.total
                    total_staff_adv += staff_adv
                if line.code == 'DEDUCTION':
                    other_deduct = other_deduct + line.total
                    total_other_deduct += other_deduct
                if line.code == 'IT':
                    income_tax = income_tax + line.total
                    total_income_tax += income_tax
                if line.code == 'BONUS':
                    bonus = bonus + line.total
                    total_bonus += bonus
                if line.code == 'FXA':
                    fixed_allo = fixed_allo + line.total
                    total_fixed_allo += fixed_allo
                if line.code == 'BASIC':
                    basic_salary = basic_salary + line.total
                    total_basic_salary += basic_salary
                if line.code == 'NET':
                    total_payable = total_payable + line.total
                    grand_total_payable += total_payable
                # if line.code == 'GROSS':
                #     salary_payable = salary_payable + line.total
                #     total_salary_payable += salary_payable
            employer_records = self.env['pf.employee.employer'].search(
                [('employee_id', '=', payslip.employee_id.id), ('pf_date', '>=', payslip.date_from),
                 ('pf_date', '<=', payslip.date_to)])
            for rec in employer_records:
                pf_till = rec.remaining_amount
                total_pf_till += pf_till
            sheet.write(row, col + 13, fixed_allo, cell_format)
            sheet.write(row, col + 14, bonus, cell_format)
            sheet.write(row, col + 15, basic_salary, cell_format)
            sheet.write(row, col + 16, house_rent_allo, cell_format)
            sheet.write(row, col + 17, utility_allo, cell_format)
            sheet.write(row, col + 18, number_of_days, cell_format)
            sheet.write(row, col + 19, round(salary_payable, 2), cell_format)
            sheet.write(row, col + 20, overtime, cell_format)
            sheet.write(row, col + 21, loan, cell_format)
            loan_sum += loan
            sheet.write(row, col + 22, increment, cell_format)
            sheet.write(row, col + 23, reimbursement, cell_format)
            sheet.write(row, col + 24, arrear, cell_format)
            sheet.write(row, col + 25, pf_empl, cell_format)
            sheet.write(row, col + 26, eobi_empl, cell_format)
            sheet.write(row, col + 27, pessi_empl, cell_format)
            sheet.write(row, col + 28, pf_empr, cell_format)
            sheet.write(row, col + 29, eobi_empr, cell_format)
            sheet.write(row, col + 30, staff_adv, cell_format)
            sheet.write(row, col + 31, other_deduct, cell_format)
            sheet.write(row, col + 32, income_tax, cell_format)
            sheet.write(row, col + 33, total_payable, cell_format)
            row += 1

        sheet.write(row, col + 11, 'Total', text_wrap)
        sheet.write(row, col + 12, round(total_wage), cell_for)
        sheet.write(row, col + 13, round(total_fixed_allo), cell_for)
        sheet.write(row, col + 14, round(total_bonus), cell_for)
        sheet.write(row, col + 15, round(total_basic_salary), cell_for)
        sheet.write(row, col + 16, round(total_house_rent), cell_for)
        sheet.write(row, col + 17, round(total_utility_allo), cell_for)
        sheet.write(row, col + 19, round(total_salary_payable), cell_for)
        sheet.write(row, col + 20, round(total_overtime), cell_for)
        sheet.write(row, col + 21, round(loan_sum), cell_for)
        sheet.write(row, col + 22, round(total_increment), cell_for)
        sheet.write(row, col + 23, round(total_reimbursement), cell_for)
        sheet.write(row, col + 24, round(total_arrear), cell_for)
        sheet.write(row, col + 25, round(total_pf_empl), cell_for)
        sheet.write(row, col + 26, round(total_eobi_empl), cell_for)
        sheet.write(row, col + 27, round(total_pessi_empl), cell_for)
        sheet.write(row, col + 28, round(total_pf_empr), cell_for)
        sheet.write(row, col + 29, round(total_eobi_empr), cell_for)
        sheet.write(row, col + 30, round(total_staff_adv), cell_for)
        sheet.write(row, col + 31, round(total_other_deduct), cell_for)
        sheet.write(row, col + 32, round(total_income_tax), cell_for)
        sheet.write(row, col + 33, round(grand_total_payable), cell_for)
        # sheet.write(row, col + 31, total_pf_till, cell_format)
