from datetime import datetime

from odoo import models


class ReportXlsxLoanVehicle(models.AbstractModel):
    _name = 'report.pakgulf_loan_report.action_vehicle_loan_xlsx'
    _description = 'Report Wizard For Excel Xlsx File'
    _inherit = 'report.report_xlsx.abstract'

    def generate_xlsx_report(self, workbook, data, objs):
        sheet = workbook.add_worksheet('Loan Acquired for Vehicles Loan')
        bold = workbook.add_format({'bold': True})
        text_wrap2 = workbook.add_format()
        text_wrap2.set_bold()
        text_wrap2.set_align('center')
        text_wrap2.set_border()

        text_wrap1 = workbook.add_format()
        text_wrap1.set_bold()
        text_wrap1.set_bg_color('#dcdcdc')
        text_wrap1.set_font_color('black')
        text_wrap1.set_align('center')
        text_wrap1.set_text_wrap()
        text_wrap1.set_border()

        text_wrap = workbook.add_format()
        text_wrap.set_align('center')
        text_wrap.set_bold()
        text_wrap.set_font_color('black')
        text_wrap.set_bg_color('gray')
        text_wrap.set_text_wrap()
        text_wrap.set_border()

        text_wrap3 = workbook.add_format()
        text_wrap3.set_align('left')
        text_wrap3.set_bold()
        text_wrap3.set_border()
        text_wrap3.set_font_color('black')
        text_wrap3.set_text_wrap()



        cell_format = workbook.add_format()
        cell_format.set_align('center')

        sheet.set_column('A:A', 10)
        sheet.set_column('B:C', 25)
        sheet.set_column('D:R', 15)


        # Headers
        sheet.merge_range(2, 2, 3, 4, 'Loan Acquired for Vehicles Loan', text_wrap1)
        sheet.write(1, 0, 'From Date:', text_wrap3)
        sheet.write(3, 0, 'To Date:', text_wrap3)
        sheet.write(1, 6, 'Generated By:', text_wrap3)
        sheet.write(2, 6, self.env.user.name)
        sheet.write(3, 6, 'Print On:', text_wrap3)
        sheet.write(4, 6, str(datetime.now()))
        record = self.env['pak.vehicle.loan.report'].search([], limit=1, order="id desc")
        sheet.write(1, 1, str(record.from_date), text_wrap3)
        sheet.write(3, 1, str(record.to_date), text_wrap3)

        row = 8
        col = 0
        sheet.write(row, col, 'Sr. No.', text_wrap)
        sheet.write(row, col + 1, 'Employee Code', text_wrap)
        sheet.write(row, col + 2, 'Employee Name', text_wrap)
        sheet.write(row, col + 3, 'Loan Number', text_wrap)
        sheet.write(row, col + 4, 'Date', text_wrap)
        sheet.write(row, col + 5, 'Loan Amount', text_wrap)
        sheet.write(row, col + 6, 'Total Installments', text_wrap)
        sheet.write(row, col + 7, 'Out. Std. Installments', text_wrap)
        sheet.write(row, col + 8, 'Deduction Per Montrh', text_wrap)
        sheet.write(row, col + 9, 'Cumulative Paid Amount', text_wrap)
        sheet.write(row, col + 10, 'Balance Amount Payable', text_wrap)
        sheet.write(row, col + 11, 'Interest paid in current Month', text_wrap)
        sheet.write(row, col + 12, 'Principle paid in current Month', text_wrap)
        sheet.write(row, col + 13, 'Paid Lum Sum', text_wrap)
        sheet.write(row, col + 14, 'Addition In Loan (if any)', text_wrap)
        sheet.write(row, col + 15, 'Remarks', text_wrap)


        row = 9
        col = 0


